### ISSUE TITLE
[BUG] `Poetry install` commend raises error for `h5py`

### ISSUE THREAD

**Issue by Alek050** [floodlight-sports/floodlight#127]
**Checklist**
- [x] I've updated to the latest version of floodlight
- [x] I've checked if a similar issue exists

**Describe the bug**
when cloning the floodlight code locally and running `poetry install`,  the installation of packages fails (see screenshots below).

**To Reproduce**
Open a new project, clone the floodlight code, run `poetry install` with poetry version 1.3.2 and python version 3.10.10

**Expected behavior**
A `CalledProcessError` is raised when running `poetry install`. `h5py` can not be installed. See screenshots below for terminal output.

**Screenshots**
<img width="734" alt="Screenshot 2023-02-17 at 15 31 10" src="https://user-images.githubusercontent.com/49450063/219683212-c1680472-0d0d-480d-bd2e-c5566a8f90ec.png">
<img width="1717" alt="Screenshot 2023-02-17 at 15 31 34" src="https://user-images.githubusercontent.com/49450063/219683238-3374ebb7-09a2-4fab-a171-d10639102af4.png">
<img width="1714" alt="Screenshot 2023-02-17 at 15 31 59" src="https://user-images.githubusercontent.com/49450063/219683284-378c4178-33d6-48cd-ab53-24a66e632dd1.png">
<img width="1714" alt="Screenshot 2023-02-17 at 15 32 32" src="https://user-images.githubusercontent.com/49450063/219683327-590d3840-a943-430f-94f8-9381d5ad6883.png">
<img width="1229" alt="Screenshot 2023-02-17 at 15 32 52" src="https://user-images.githubusercontent.com/49450063/219683342-030efd12-dc84-4aba-ba77-cf83c2a43681.png">

**Platform (please complete the following information):**
 - OS: MacOs (Ventura 13.1)
 - Python Version 3.10.10 (see screenshots)

**Additional context**
Possible solution: After running `poetry update`, updating the package dependencies, everything works fine. This would also make it possible to run the package using Python 3.11 (latest stable version).

**Comment by draabe** [comment]
Hi @Alek050,

this seems to be a poetry issue with fresh Python versions (see this: https://github.com/python-poetry/poetry/issues/2746 ). My only guess would be to downgrade your Python version. You state that you use Python 3.10.10, but on your screenshots it says Python 3.11.1 is used for creating the venv by poetry, so maybe you've not activated the older version?

Also thanks for the hint, we'll be updating our dependencies soon!

**Comment by Alek050** [comment]
Hey @draabe ,

Thanks for your response. As far as I can tell it says `The current Python version 3.11.1 is not supported by the...` And than continues with `Trying to find and use a compatible version`, `Using Python 3.10 (3.10.10)`, `Creating virtualenv floodligth-bcwokx5m-3.10 in ...`. This seems to me that poetry is using Python 3.10 for creating the environment. Am I missing something?

**Comment by draabe** [comment]
My bad, I missed that. Another idea would be to delete the poetry cache which, on Windows, is at "...\AppData\Local\pypoetry\Cache\...", but otherwise, I'm running out of ideas tbh.
