### ISSUE TITLE
[DOCS] Tracab Data Documentation

### ISSUE THREAD

**Issue by hadisotudeh** [floodlight-sports/floodlight#129]
Hi!

The [tracbab functions](https://floodlight.readthedocs.io/en/latest/_modules/floodlight/io/tracab.html#read_position_data_dat) introduce some variables without proper documentation, as listed below:

- Ball and player speed without mentioning their units and how they are calculated from x,y, and z values.
- The meaning of the `system_id` variable.
- `SetHome`, `SetAway`, and other values that are ignored!
- There are other values than 0 and 1 for `team`, which are not explained.

Can you clarify them?

**Comment by Alek050** [comment]
Hey @hadisotudeh ,

I think a lot of your questions are very specific to tracab data. It's good to mention that, as far as I'm aware, the strength of this package is that it tries to get most information out of a data provider and normalizes the parsing in a way that you can continue your analysis regardless of what provider you use.
Although I've not yet contributed to this project, I might be able to answer some of your questions:
- The ball and player speed are added in the raw data of tracab, the units are the same as the x and y coordinates of the tracking data itself. Admittately, it could be mentioned in the docs. The precise calculation is determined by Tracab and I'm not sure how they did it, but you could of course use the x and y data to calculcate your own speeds. 
- The `system_id` is not used later on in the code, so it should be replaced with `_`. It's a rather technical variable that relates to the way the data is obtained. Tracab creates "spots" in their software, here called `system_id`'s where a player could be tracked. A person in the stadion links names/players to a spot in their software. When a player 'lost', for instance when he leaves the pitch or all players get close and the software loses track of who is who, the names/players need to be linked again to a spot. This makes it possible that the same player is represented at different spots or `system_id`'s during a game. However, as mentioned before, the variable is not used and not really interesting after parsing the data.
- `SetHome` and `SetAway` can be recomputed from the `bal["posession"]`, the other variables, like a "Whistle" are not really interesting and in my experience lack reliability (as do `SetHome` and `SetAway`).
- The other values can be -1 (`system_id` is not used, no player is tracked) or 2 or 3, which are the referees and the linesman, however, also not really interesting I would say.

I hope this helps you.

**Comment by hadisotudeh** [comment]
Hi @Alek050, 

Thanks for your answer. It is interesting to know why Tracab keeps this information in their dat files while they are not of any use and maybe even more cause confusion!

**Comment by draabe** [comment]
Hi @hadisotudeh,

I agree with everything @Alek050 has said, thanks for helping out! ``SetHome`` and ``SetAway`` are also more of "internal" variables, depending on whether somebody clicked the possession logger during the acquisition process. I could imagine they keep this add'l information from the data acquisition process for debugging or quality assurance purposes, but who knows.

The ``system_id`` could well be replaced by ``_`` in the code as we regard it anyhow. We kept it just _because_ the file format is so confusing, ie. to explicitly know what information comes from what data chunk.
