### ISSUE TITLE
[Feature request]: summary() or info() function for teamsheets

### ISSUE THREAD

**Issue by robertreingit** [floodlight-sports/floodlight#136]
For example:

(
    xy_objects,
    possession_objects,
    ballstatus_objects,
    teamsheets,
    pitch,
) = dfl.read_position_data_xml(fpath, fpath_info)
teamsheets['Home'].summary()

Providing a short descriptive summary of the game.

**Comment by draabe** [comment]
Hi @robertreingit,

the ``Teamsheet`` object does not contain enough information to support a summary function for the entire game. But you may want to look into the "print" methods of each core object to see a summary of the data.
