### ISSUE TITLE
JOSS review: No setup.py?

### ISSUE THREAD

**Issue by kanishkan91** [floodlight-sports/floodlight#83]
This project does not have a setup.py. Effectively developers are suggesting intsllation via pip only. Does this mean no public user can contribute to the code? Since this is an open source software package, I think this should include a setup.py so that users have the option to have a developer version of the code where they can make changes. I would insist on this since this is a requirement for an open source software package. Corresponding installtion instructions would also have to be added. 

https://github.com/openjournals/joss-reviews/issues/4588

**Comment by kanishkan91** [comment]
See my comment on the usage of `poetry`. You need to explicitly state that `poetry`  is the replacement for the `setup.py`. Also I would just recommend removing references to `pip install floodlight`. You should just recommend that users make use of setup.py or poetry. Else, people will run into the same problem I did.

**Comment by draabe** [comment]
@kanishkan91 please see my replies and corresponding changes from here:
https://github.com/openjournals/joss-reviews/issues/4588
https://github.com/floodlight-sports/floodlight/issues/85

**Comment by kanishkan91** [comment]
Thanks. Closing.
