### ISSUE TITLE
Joss review: Need more documentation on poetry. Also, deprecate pip install instructions

### ISSUE THREAD

**Issue by kanishkan91** [floodlight-sports/floodlight#85]
I see that the developers have used poetry as the means of inviting development. However, I think there need to be step by step instructions on how to use poetry for contribution. Forgive my ignorance, but I could not follow the current instructions to get a version of this package set up on my machine. I would recommend that the developers add the setup.py file in addition to poetry for this reason.   

https://github.com/openjournals/joss-reviews/issues/4588

**Comment by kanishkan91** [comment]
In particular I think you need to explicitly state that poetry is a replacement for setup.py. And you need to mention that the command `poetry install` replaces `pip install -e.`

**Comment by draabe** [comment]
@kanishkan91 we have instructions for installation in dev mode both in the [CONTRIBUTING.md](https://github.com/floodlight-sports/floodlight/blob/main/CONTRIBUTING.md#Development) (short version) as well as the [extended contributing guide](https://floodlight.readthedocs.io/en/latest/guides/contrib_manual.html#developing) (long version), both explaining the installation of ``poetry``. I see that for users familiar with setup.py, this might be a bit confusing. I've altered the descriptions in both files at the appropriate places as follows:

- *CONTRIBUTING.md*: "We use *poetry* for development and dependency management, which is based on the static `pyproject.toml` file and replaces `setup.py`. With *poetry*, setting up your local dev environment is rather straightforward: [...]"
- *Contributing Guide*: "[...] Luckily, there's a tool called *poetry* which simplifies this a lot. *poetry* works with the static ``pyproject.toml`` file containing project metadata, and replaces the usage of ``setup.py`` files. Thus, the first step is to install poetry! [...]"

**Comment by kanishkan91** [comment]
Looks great. Thanks for the additions!
