### ISSUE TITLE
JOSS review: Comment on low test coverage for datasets.py?

### ISSUE THREAD

**Issue by kanishkan91** [floodlight-sports/floodlight#90]
Only 20% of the lines in this file seem to be covered by a test. Can the authors comment on this? There is likely a reason for this and I don't want to force the authors to write pedantic test cases. So, an explanation would suffice.

https://github.com/openjournals/joss-reviews/issues/4588

**Comment by draabe** [comment]
That is correct. Most of the functionality of the datasets is accessing URLs and downloading data, then activating the corresponding data parser (which is located and tested in the ``io.statsbomb`` submodule). So we felt that more test cases would either only effectively test the workings of dependencies (such as ``urllib`` or ``h5py``) or involve the download of large files.

**Comment by kanishkan91** [comment]
Thanks! Just needed a comment for the review. Closing this now.
